// <auto-generated />
namespace Gighub.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addForeignkeyPropertiesToGig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addForeignkeyPropertiesToGig));
        
        string IMigrationMetadata.Id
        {
            get { return "201612290308080_addForeignkeyPropertiesToGig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
